# Configuration for actions/labeler

backend:
  - changed-files:
      - any-glob-to-any-file: 'backend/**/*'

frontend:
  - changed-files:
      - any-glob-to-any-file: 'frontend/**/*'

documentation:
  - changed-files:
      - any-glob-to-any-file: 'docs/**/*'
      - any-glob-to-any-file: '*.md'

database:
  - changed-files:
      - any-glob-to-any-file: 'database/**/*'

workflows:
  - changed-files:
      - any-glob-to-any-file: '.github/workflows/**/*'
