spring.application.name=Hackathon

spring.config.import=optional:file:./hackathon.env[.properties]

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=Hackathon;encrypt=true;trustServerCertificate=true

spring.datasource.username=sa
spring.datasource.password=12345
brevo.api.key = ${BREVO_API_KEY}

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver